PREFIX iopce: <http://www.w3id.org/iopce#>
PREFIX opm: <http://www.w3id.org/opm#>
PREFIX schema: <https://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX BMS: <http://www.example.org/BMS#>

SELECT ?condition_index_value ?evaluation
WHERE {
    #get bridge actual condition index
	{BMS:PR-04-B015 iopce:indice_de_condicion ?condition_index . 			
    ?condition_index opm:hasPropertyState ?condition_index_state.
    ?condition_index_state a opm:CurrentPropertyState;
    	schema:value ?condition_index_value ;
        prov:generatedAtTime ?evaluation .}
    UNION
    #get bridge previous condition indexes
    {BMS:PR-04-B015 iopce:indice_de_condicion ?condition_index . 			
    ?condition_index opm:hasPropertyState ?condition_index_state.
    ?condition_index_state a opm:PropertyState;
    	schema:value ?condition_index_value ;
        prov:generatedAtTime ?evaluation .}
    
} ORDER BY DESC(?evaluation)